### ISSUE TITLE
log message numbers

### ISSUE THREAD

**Issue by YashasSamaga** [maddinat0r/samp-log-core#10]
[feature-request]

This similar to what most compilers do: every warning/error has a number associated with it. It would be great if plugins using samp-log-core were given the option of specifying a number along with the log message. This would allow the scripter to selectively disable/enable specific log messages.

**Comment by maddinat0r** [comment]
I'm not sure if adding this is a good idea, especially for errors. Errors indicate a mistake at runtime, often caused by the scripter misusing a native function. Disabling errors would just hide away the actual problem, instead of the scripter fixing this in his script.

Disabling specific warnings isn't that much wrong, as they're only meant to warn the user/scripter. I actually have a warning log message in the MySQL plugin regarding duplicate connections that can be enabled/disabled through a native, so adding this would eliminate the need for that.

**Comment by YashasSamaga** [comment]
If someone wants to debug a specific native, they wouldn't want to enable all the debug messages. It would be helpful for the user to only enable the debug messages corresponding to the native.

**Comment by maddinat0r** [comment]
As an example: there are over 150 debug log messages in the MySQL plugin. A user would have to disable over 100 lines of debug logs by hand if each of them would be numbered to properly print debug logs for a single native only.
